--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/CustomDeathMessage
build-by-default: true
branches:
- main
projects:
  CustomDeathMessage:
    path: ""
    libs:
      - src: Terpz710/CustomDeathMessages
        version: ^1.7
        branch: "main"
...
